service: store
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/get.handler
    events:
      - httpApi:
          path: /
          method: get
  save:
    handler: src/save.handler
    # events:
    #   - httpApi:
    #       path: /
    #       method: get

plugins:
  - serverless-offline
